version: "3.3"
services:
  api:
    build: ./api
    networks:
      - internal
    environment:
      - DATABASE_URL=postgresql://user:MyPasswordVerySecret@db:5432/forum?schema=public
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: MyPasswordVerySecret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
  thread:
    build: ./thread
    ports:
      - "80:80"
    networks:
      - internal
  sender:
    build: ./sender
    ports:
      - "8080:8080"
    networks:
      - internal
networks:
  internal:
    driver: bridge
volumes:
  db-data:
