FROM node:20-alpine AS build

WORKDIR /app

RUN npm i -g corepack@latest && corepack enable pnpm

COPY package*.json ./
RUN pnpm install

COPY . .
RUN pnpm prisma generate
RUN pnpm build

FROM node:20-alpine AS prod

WORKDIR /app

RUN npm i -g corepack@latest && corepack enable pnpm

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/prisma ./prisma

EXPOSE 3001
ENV PORT=3001

USER node

CMD pnpm prisma migrate deploy && pnpm start:prod